"use client";

import { useState, useMemo } from "react";
import { Search } from "lucide-react";

// Mapping mots-cles francais -> emojis pour la recherche
const EMOJI_NAMES: Record<string, string[]> = {
  // Smileys & visages
  sourire: ["😊", "😀", "😃", "😄", "🙂", "☺️"],
  rire: ["😂", "🤣", "😆", "😅"],
  clin: ["😉"],
  amour: ["😍", "🥰", "😘", "💕", "💗", "💖", "❤️", "💑"],
  coeur: [
    "❤️",
    "🧡",
    "💛",
    "💚",
    "💙",
    "💜",
    "🖤",
    "🤍",
    "🤎",
    "💔",
    "💕",
    "💞",
    "💓",
    "💗",
    "💖",
    "💘",
    "💝",
    "💟",
    "❣️",
    "♥️",
  ],
  bisou: ["😘", "😗", "😙", "😚", "💋"],
  langue: ["😋", "😛", "😜", "🤪", "😝"],
  cool: ["😎", "🤩", "🕶️"],
  lunettes: ["😎", "🤓", "🧐"],
  argent: ["🤑", "💰", "💵", "💶", "💷", "💴", "💲", "🏦"],
  calin: ["🤗"],
  chut: ["🤫"],
  penser: ["🤔", "💭"],
  triste: ["😢", "😭", "😞", "😔", "🙁", "😿"],
  pleure: ["😢", "😭", "😿"],
  colere: ["😠", "😡", "🤬", "😤", "💢"],
  peur: ["😨", "😰", "😱", "🫣"],
  surpris: ["😮", "😯", "😲", "😳", "🤯"],
  malade: ["😷", "🤒", "🤕", "🤢", "🤮", "🥴"],
  dormir: ["😴", "💤", "😪"],
  fete: ["🥳", "🎉", "🎊", "🪅"],
  diable: ["😈", "👿"],
  mort: ["💀", "☠️"],
  fantome: ["👻"],
  alien: ["👽", "👾", "🛸"],
  robot: ["🤖"],
  clown: ["🤡"],
  caca: ["💩"],
  singe: ["🙈", "🙉", "🙊", "🐵", "🐒"],
  chat: [
    "😺",
    "😸",
    "😹",
    "😻",
    "😼",
    "😽",
    "🙀",
    "😿",
    "😾",
    "🐱",
    "🐈",
    "🐈‍⬛",
  ],
  // Mains & gestes
  salut: ["👋", "🤚"],
  main: ["👋", "🤚", "🖐️", "✋", "🖖", "🫱", "🫲", "🫳", "🫴"],
  ok: ["👌", "🆗"],
  pouce: ["👍", "👎"],
  bravo: ["👏", "🙌", "👍"],
  poing: ["✊", "👊", "🤛", "🤜"],
  victoire: ["✌️", "🏆"],
  rock: ["🤘", "🎸"],
  prier: ["🙏"],
  muscle: ["💪"],
  ecrire: ["✍️", "🖊️", "📝"],
  applaudir: ["👏"],
  // Animaux
  chien: ["🐶", "🐕", "🦮", "🐕‍🦺", "🐩"],
  lapin: ["🐰", "🐇"],
  ours: ["🐻", "🐻‍❄️", "🧸"],
  renard: ["🦊"],
  lion: ["🦁"],
  tigre: ["🐯", "🐅"],
  cheval: ["🐴", "🐎", "🏇"],
  licorne: ["🦄"],
  cochon: ["🐷", "🐖", "🐽"],
  vache: ["🐮", "🐄"],
  poule: ["🐔", "🐓", "🐣", "🐤", "🐥"],
  oiseau: ["🐦", "🐦‍⬛", "🕊️", "🦅", "🦆", "🦢", "🦩", "🦜", "🐧"],
  poisson: ["🐟", "🐠", "🐡", "🦈", "🐬", "🐳", "🐋"],
  papillon: ["🦋"],
  abeille: ["🐝"],
  serpent: ["🐍"],
  tortue: ["🐢"],
  grenouille: ["🐸"],
  dragon: ["🐉", "🐲"],
  // Nature
  fleur: ["🌸", "💮", "🌹", "🌺", "🌻", "🌼", "🌷", "🥀", "💐", "🏵️"],
  rose: ["🌹"],
  arbre: ["🌲", "🌳", "🌴", "🎄", "🪵"],
  soleil: ["☀️", "🌞", "🌅", "🌄"],
  lune: ["🌙", "🌛", "🌜", "🌝", "🌚", "🌕", "🌖", "🌗", "🌘"],
  etoile: ["⭐", "🌟", "✨", "💫", "🌠"],
  pluie: ["🌧️", "⛈️", "🌦️", "☔", "💧"],
  neige: ["❄️", "☃️", "⛄", "🌨️"],
  arc: ["🌈"],
  feu: ["🔥", "🧯"],
  eau: ["💧", "💦", "🌊", "🏊"],
  nuage: ["☁️", "⛅", "🌤️", "🌥️"],
  // Nourriture
  pizza: ["🍕"],
  burger: ["🍔"],
  frite: ["🍟"],
  gateau: ["🎂", "🍰", "🧁"],
  chocolat: ["🍫", "🍩"],
  glace: ["🍦", "🍧", "🍨"],
  bonbon: ["🍬", "🍭"],
  fruit: ["🍎", "🍐", "🍊", "🍋", "🍌", "🍉", "🍇", "🍓", "🍒", "🍑"],
  pomme: ["🍎", "🍏"],
  banane: ["🍌"],
  raisin: ["🍇"],
  fraise: ["🍓"],
  pastèque: ["🍉"],
  cafe: ["☕", "🫖"],
  biere: ["🍺", "🍻"],
  vin: ["🍷", "🍾"],
  cocktail: ["🍸", "🍹"],
  champagne: ["🍾", "🥂"],
  sushi: ["🍣", "🍱"],
  pates: ["🍝"],
  pain: ["🍞", "🥖", "🥐", "🫓"],
  fromage: ["🧀"],
  oeuf: ["🥚", "🍳"],
  viande: ["🍖", "🍗", "🥩", "🥓"],
  salade: ["🥗"],
  soupe: ["🍜", "🥣"],
  // Voyages & lieux
  avion: ["✈️", "🛩️", "🛫", "🛬"],
  voiture: ["🚗", "🚙", "🏎️"],
  bus: ["🚌", "🚎"],
  train: ["🚂", "🚃", "🚄", "🚅", "🚆", "🚇", "🚈", "🚝"],
  bateau: ["⛵", "🚤", "🛥️", "🚢", "🛳️"],
  velo: ["🚲", "🚴"],
  moto: ["🏍️", "🛵"],
  fusee: ["🚀"],
  maison: ["🏠", "🏡", "🏘️"],
  immeuble: ["🏢", "🏬", "🏗️"],
  hopital: ["🏥"],
  ecole: ["🏫"],
  eglise: ["⛪"],
  mosquee: ["🕌"],
  montagne: ["🏔️", "⛰️", "🌋"],
  plage: ["🏖️", "🏝️"],
  camping: ["🏕️", "⛺"],
  monde: ["🌍", "🌎", "🌏", "🗺️"],
  // Activites & sports
  foot: ["⚽"],
  basket: ["🏀"],
  tennis: ["🎾"],
  natation: ["🏊"],
  surf: ["🏄"],
  ski: ["⛷️", "🎿", "🏂"],
  musique: ["🎵", "🎶", "🎼", "🎧", "🎤", "🎹", "🎷", "🎺", "🎸", "🥁"],
  cinema: ["🎬", "🎥", "📽️", "🎞️"],
  art: ["🎨", "🖌️", "🖼️"],
  jeu: ["🎮", "🕹️", "🎲", "♟️", "🧩"],
  dice: ["🎲"],
  theatre: ["🎭"],
  magie: ["🪄", "✨"],
  // Objets
  telephone: ["📱", "📞", "☎️"],
  ordinateur: ["💻", "🖥️", "⌨️"],
  camera: ["📷", "📸", "📹", "🎥"],
  livre: ["📖", "📚", "📓", "📒", "📕", "📗", "📘", "📙"],
  crayon: ["✏️", "🖊️", "🖋️", "📝"],
  cle: ["🔑", "🗝️"],
  cadenas: ["🔒", "🔓"],
  ampoule: ["💡"],
  horloge: ["⏰", "⏱️", "⏲️", "🕐"],
  calendrier: ["📅", "📆", "🗓️"],
  boite: ["📦", "📫", "📬", "📭", "📮"],
  cadeau: ["🎁"],
  trophee: ["🏆", "🥇", "🥈", "🥉", "🏅", "🎖️"],
  medaille: ["🏅", "🎖️", "🥇", "🥈", "🥉"],
  couronne: ["👑"],
  diamant: ["💎"],
  // Symboles
  oui: ["✅", "✔️", "☑️", "👍"],
  non: ["❌", "❎", "🚫", "⛔", "👎"],
  attention: ["⚠️", "🚨", "❗"],
  question: ["❓", "❔"],
  info: ["ℹ️"],
  fleche: ["➡️", "⬅️", "⬆️", "⬇️", "↗️", "↘️", "↙️", "↖️", "↕️", "↔️"],
  plus: ["➕"],
  moins: ["➖"],
  infini: ["♾️"],
  recyclage: ["♻️"],
  paix: ["☮️", "✌️", "🕊️"],
  // Drapeaux
  france: ["🇫🇷"],
  usa: ["🇺🇸"],
  angleterre: ["🇬🇧"],
  allemagne: ["🇩🇪"],
  espagne: ["🇪🇸"],
  italie: ["🇮🇹"],
  portugal: ["🇵🇹"],
  belgique: ["🇧🇪"],
  suisse: ["🇨🇭"],
  canada: ["🇨🇦"],
  japon: ["🇯🇵"],
  maroc: ["🇲🇦"],
  algerie: ["🇩🇿"],
  tunisie: ["🇹🇳"],
  senegal: ["🇸🇳"],
  bresil: ["🇧🇷"],
};

const EMOJI_CATEGORIES = [
  {
    name: "Frequents",
    icon: "⭐",
    emojis: [
      "😊",
      "😂",
      "❤️",
      "👍",
      "🎉",
      "🔥",
      "💪",
      "✅",
      "👏",
      "🙏",
      "💯",
      "⭐",
      "🚀",
      "💰",
      "🎯",
      "😍",
      "🤝",
      "👋",
      "✨",
      "💡",
      "😅",
      "🤣",
      "😎",
      "🥳",
      "💕",
      "🙌",
      "😘",
      "🤩",
      "💥",
      "👊",
    ],
  },
  {
    name: "Smileys",
    icon: "😊",
    emojis: [
      // Heureux
      "😀",
      "😃",
      "😄",
      "😁",
      "😆",
      "😅",
      "🤣",
      "😂",
      "🙂",
      "🙃",
      "😉",
      "😊",
      "😇",
      "🥹",
      "☺️",
      // Amour
      "🥰",
      "😍",
      "🤩",
      "😘",
      "😗",
      "😚",
      "😙",
      // Langue
      "🥲",
      "😋",
      "😛",
      "😜",
      "🤪",
      "😝",
      // Mains sur visage
      "🫢",
      "🤭",
      "🫡",
      "🤫",
      "🤔",
      "🫣",
      // Neutre / sceptique
      "🤐",
      "🤨",
      "😐",
      "😑",
      "😶",
      "🫥",
      "😶‍🌫️",
      // Negatif leger
      "😏",
      "😒",
      "🙄",
      "😬",
      "😮‍💨",
      "🤥",
      // Triste / fatigue
      "🫠",
      "😌",
      "😔",
      "😪",
      "🤤",
      "😴",
      // Malade
      "😷",
      "🤒",
      "🤕",
      "🤢",
      "🤮",
      "🥴",
      "😵",
      "😵‍💫",
      "🤯",
      // Deguise / fun
      "🤠",
      "🥳",
      "🥸",
      "😎",
      "🤓",
      "🧐",
      // Inquiet / triste
      "😕",
      "🫤",
      "😟",
      "🙁",
      "☹️",
      "😮",
      "😯",
      "😲",
      "😳",
      "🥺",
      "🥹",
      "😦",
      "😧",
      "😨",
      "😰",
      "😥",
      "😢",
      "😭",
      // Colere
      "😱",
      "😖",
      "😣",
      "😞",
      "😓",
      "😩",
      "😫",
      "🥱",
      "😤",
      "😡",
      "😠",
      "🤬",
      // Creatures
      "😈",
      "👿",
      "💀",
      "☠️",
      "💩",
      "🤡",
      "👹",
      "👺",
      "👻",
      "👽",
      "👾",
      "🤖",
      // Chats
      "😺",
      "😸",
      "😹",
      "😻",
      "😼",
      "😽",
      "🙀",
      "😿",
      "😾",
      // Singes
      "🙈",
      "🙉",
      "🙊",
      // Argent
      "🤑",
      // Calin
      "🤗",
    ],
  },
  {
    name: "Personnes",
    icon: "👋",
    emojis: [
      // Mains
      "👋",
      "🤚",
      "🖐️",
      "✋",
      "🖖",
      "🫱",
      "🫲",
      "🫳",
      "🫴",
      "🫷",
      "🫸",
      "👌",
      "🤌",
      "🤏",
      "✌️",
      "🤞",
      "🫰",
      "🤟",
      "🤘",
      "🤙",
      "👈",
      "👉",
      "👆",
      "🖕",
      "👇",
      "☝️",
      "🫵",
      "👍",
      "👎",
      "✊",
      "👊",
      "🤛",
      "🤜",
      "👏",
      "🙌",
      "🫶",
      "👐",
      "🤲",
      "🤝",
      "🙏",
      "✍️",
      "💅",
      "🤳",
      "💪",
      "🦾",
      "🦿",
      "🦵",
      "🦶",
      // Corps
      "👂",
      "🦻",
      "👃",
      "🧠",
      "🫀",
      "🫁",
      "🦷",
      "🦴",
      "👀",
      "👁️",
      "👅",
      "👄",
      "🫦",
      "💋",
      // Personnes
      "👶",
      "🧒",
      "👦",
      "👧",
      "🧑",
      "👱",
      "👨",
      "🧔",
      "👩",
      "🧓",
      "👴",
      "👵",
      "🙍",
      "🙎",
      "🙅",
      "🙆",
      "💁",
      "🙋",
      "🧏",
      "🙇",
      "🤦",
      "🤷",
      "👮",
      "🕵️",
      "💂",
      "🥷",
      "👷",
      "🫅",
      "🤴",
      "👸",
      "👳",
      "👲",
      "🧕",
      "🤵",
      "👰",
      "🤰",
      "🫄",
      "🤱",
      "👼",
      "🎅",
      "🤶",
      "🦸",
      "🦹",
      "🧙",
      "🧚",
      "🧛",
      "🧜",
      "🧝",
      "🧞",
      "🧟",
      "🧑‍🍳",
      "🧑‍🎓",
      "🧑‍🏫",
      "🧑‍⚕️",
      "🧑‍🌾",
      "🧑‍💻",
      "🧑‍🎤",
      "🧑‍🎨",
      "🧑‍✈️",
      "🧑‍🚀",
      "🧑‍🚒",
      // Famille
      "💑",
      "👩‍❤️‍👨",
      "💏",
      "👪",
      "👨‍👩‍👦",
      "👨‍👩‍👧",
    ],
  },
  {
    name: "Animaux",
    icon: "🐶",
    emojis: [
      // Mammiferes
      "🐶",
      "🐕",
      "🦮",
      "🐕‍🦺",
      "🐩",
      "🐺",
      "🦊",
      "🦝",
      "🐱",
      "🐈",
      "🐈‍⬛",
      "🦁",
      "🐯",
      "🐅",
      "🐆",
      "🐴",
      "🫎",
      "🫏",
      "🦄",
      "🦓",
      "🐮",
      "🐂",
      "🐃",
      "🐄",
      "🦬",
      "🐷",
      "🐖",
      "🐗",
      "🐽",
      "🐏",
      "🐑",
      "🐐",
      "🐪",
      "🐫",
      "🦙",
      "🦒",
      "🐘",
      "🦣",
      "🦏",
      "🦛",
      "🐭",
      "🐁",
      "🐀",
      "🐹",
      "🐰",
      "🐇",
      "🐿️",
      "🦫",
      "🦔",
      "🦇",
      "🐻",
      "🐻‍❄️",
      "🐨",
      "🐼",
      "🦥",
      "🦦",
      "🦨",
      "🦘",
      "🦡",
      // Oiseaux
      "🐔",
      "🐓",
      "🐣",
      "🐤",
      "🐥",
      "🐦",
      "🐦‍⬛",
      "🐧",
      "🕊️",
      "🦅",
      "🦆",
      "🦢",
      "🦉",
      "🦤",
      "🪶",
      "🦩",
      "🦜",
      "🪽",
      // Reptiles & marins
      "🐸",
      "🐊",
      "🐢",
      "🦎",
      "🐍",
      "🐉",
      "🐲",
      "🐳",
      "🐋",
      "🐬",
      "🦭",
      "🐟",
      "🐠",
      "🐡",
      "🦈",
      "🐙",
      "🐚",
      "🪸",
      "🦀",
      "🦞",
      "🦐",
      "🦑",
      "🪼",
      // Insectes
      "🐌",
      "🦋",
      "🐛",
      "🐜",
      "🐝",
      "🪲",
      "🐞",
      "🦗",
      "🪳",
      "🕷️",
      "🕸️",
      "🦂",
      "🦟",
      "🪰",
      "🪱",
      "🦠",
      // Plantes & nature
      "💐",
      "🌸",
      "💮",
      "🏵️",
      "🌹",
      "🥀",
      "🌺",
      "🌻",
      "🌼",
      "🌷",
      "🪻",
      "🌱",
      "🪴",
      "🌲",
      "🌳",
      "🌴",
      "🌵",
      "🎋",
      "🎍",
      "🌾",
      "🌿",
      "☘️",
      "🍀",
      "🍁",
      "🍂",
      "🍃",
      "🪹",
      "🪺",
      "🪵",
      "🍄",
      "🌰",
      "🪨",
      "🌍",
      "🌎",
      "🌏",
      // Meteo
      "🌑",
      "🌒",
      "🌓",
      "🌔",
      "🌕",
      "🌖",
      "🌗",
      "🌘",
      "🌙",
      "🌚",
      "🌛",
      "🌜",
      "🌝",
      "🌞",
      "⭐",
      "🌟",
      "🌠",
      "🌌",
      "☁️",
      "⛅",
      "⛈️",
      "🌤️",
      "🌥️",
      "🌦️",
      "🌧️",
      "🌨️",
      "🌩️",
      "🌪️",
      "🌫️",
      "🌬️",
      "🌈",
      "☂️",
      "☔",
      "⚡",
      "❄️",
      "☃️",
      "⛄",
      "☄️",
      "🌊",
    ],
  },
  {
    name: "Nourriture",
    icon: "🍕",
    emojis: [
      // Fruits
      "🍎",
      "🍏",
      "🍐",
      "🍊",
      "🍋",
      "🍋‍🟩",
      "🍌",
      "🍉",
      "🍇",
      "🍓",
      "🫐",
      "🍈",
      "🍒",
      "🍑",
      "🥭",
      "🍍",
      "🥥",
      "🥝",
      "🍅",
      // Legumes
      "🍆",
      "🥑",
      "🫛",
      "🥦",
      "🥬",
      "🥒",
      "🌶️",
      "🫑",
      "🌽",
      "🥕",
      "🫒",
      "🧄",
      "🧅",
      "🥔",
      "🍠",
      "🫚",
      "🫘",
      // Cereales
      "🍞",
      "🥖",
      "🫓",
      "🥨",
      "🥯",
      "🥐",
      "🧇",
      "🥞",
      // Proteines
      "🧀",
      "🍖",
      "🍗",
      "🥩",
      "🥓",
      "🥚",
      "🍳",
      // Plats
      "🍕",
      "🍔",
      "🍟",
      "🌭",
      "🥪",
      "🌮",
      "🌯",
      "🫔",
      "🥙",
      "🧆",
      "🥘",
      "🍲",
      "🫕",
      "🥣",
      "🥗",
      "🍿",
      "🧈",
      "🫙",
      // Asiatique
      "🍜",
      "🍝",
      "🍣",
      "🍱",
      "🥟",
      "🍤",
      "🍙",
      "🍚",
      "🍛",
      "🍘",
      "🍥",
      "🥠",
      "🥡",
      "🫰",
      // Desserts
      "🍦",
      "🍧",
      "🍨",
      "🍩",
      "🍪",
      "🎂",
      "🍰",
      "🧁",
      "🥧",
      "🍫",
      "🍬",
      "🍭",
      "🍮",
      "🍯",
      // Boissons
      "🍼",
      "🥛",
      "☕",
      "🫖",
      "🍵",
      "🧃",
      "🥤",
      "🧋",
      "🍺",
      "🍻",
      "🥂",
      "🍷",
      "🥃",
      "🍸",
      "🍹",
      "🧉",
      "🍾",
      "🫗",
      "🏺",
      // Ustensiles
      "🍽️",
      "🍴",
      "🥄",
      "🔪",
      "🫕",
      "🧊",
    ],
  },
  {
    name: "Voyages",
    icon: "✈️",
    emojis: [
      // Transport terrestre
      "🚗",
      "🚙",
      "🚕",
      "🚌",
      "🚎",
      "🏎️",
      "🚓",
      "🚑",
      "🚒",
      "🚐",
      "🛻",
      "🚚",
      "🚛",
      "🚜",
      "🏍️",
      "🛵",
      "🛺",
      "🚲",
      "🛴",
      "🛹",
      "🛼",
      // Transport ferroviaire
      "🚂",
      "🚃",
      "🚄",
      "🚅",
      "🚆",
      "🚇",
      "🚈",
      "🚉",
      "🚝",
      "🚞",
      // Transport aerien
      "✈️",
      "🛩️",
      "🛫",
      "🛬",
      "🪂",
      "💺",
      "🚀",
      "🛸",
      "🛰️",
      // Transport maritime
      "⛵",
      "🚤",
      "🛥️",
      "🛳️",
      "⛴️",
      "🚢",
      "⚓",
      // Signalisation
      "🚧",
      "🚦",
      "🚥",
      "🛑",
      "⛽",
      "🅿️",
      // Lieux
      "🏠",
      "🏡",
      "🏘️",
      "🏚️",
      "🏗️",
      "🏢",
      "🏬",
      "🏣",
      "🏤",
      "🏥",
      "🏦",
      "🏨",
      "🏩",
      "🏪",
      "🏫",
      "🏛️",
      "💒",
      "⛪",
      "🕌",
      "🛕",
      "🕍",
      "⛩️",
      "🕋",
      // Monuments
      "🗼",
      "🗽",
      "🗿",
      "🏰",
      "🏯",
      "🏟️",
      // Nature / paysage
      "🏔️",
      "⛰️",
      "🌋",
      "🗻",
      "🏕️",
      "🏖️",
      "🏜️",
      "🏝️",
      "🏞️",
      // Meteo & ciel
      "🌅",
      "🌄",
      "🌠",
      "🎇",
      "🎆",
      "🌇",
      "🌆",
      "🏙️",
      "🌃",
      "🌌",
      "🌉",
      "🌁",
    ],
  },
  {
    name: "Activites",
    icon: "⚽",
    emojis: [
      // Sports ballon
      "⚽",
      "🏀",
      "🏈",
      "⚾",
      "🥎",
      "🎾",
      "🏐",
      "🏉",
      "🥏",
      // Sports raquette & precision
      "🎱",
      "🪀",
      "🏓",
      "🏸",
      "🏒",
      "🥍",
      "🏑",
      // Combat
      "🥊",
      "🥋",
      "🤺",
      // But & filet
      "🥅",
      "⛳",
      "🏹",
      "🎣",
      "🤿",
      "🪃",
      // Hiver
      "🥌",
      "🛷",
      "🎿",
      "⛷️",
      "🏂",
      // Gym & fitness
      "🪂",
      "🏋️",
      "🤸",
      "⛹️",
      "🤾",
      "🏇",
      // Bien-etre
      "🧘",
      "🧗",
      // Nautique
      "🏄",
      "🏊",
      "🤽",
      "🚣",
      "🧑‍🚣",
      // Velo
      "🚴",
      "🚵",
      // Sports meca
      "🏎️",
      "🏍️",
      // Arts & spectacle
      "🎪",
      "🎭",
      "🎨",
      "🖌️",
      "🖼️",
      // Cinema & media
      "🎬",
      "🎥",
      "📽️",
      "🎞️",
      // Musique
      "🎤",
      "🎧",
      "🎼",
      "🎵",
      "🎶",
      "🎹",
      "🥁",
      "🪘",
      "🎷",
      "🎺",
      "🪗",
      "🎸",
      "🪕",
      "🎻",
      "🪈",
      // Jeux
      "🎲",
      "♟️",
      "🎯",
      "🎳",
      "🎮",
      "🕹️",
      "🧩",
      "🪄",
      "🪅",
      // Evenements
      "🎉",
      "🎊",
      "🎈",
      "🎀",
      "🎁",
      "🎗️",
      "🎟️",
      "🎫",
      // Trophees
      "🏆",
      "🥇",
      "🥈",
      "🥉",
      "🏅",
      "🎖️",
      "🎓",
    ],
  },
  {
    name: "Objets",
    icon: "💡",
    emojis: [
      // Tech
      "📱",
      "📲",
      "💻",
      "🖥️",
      "🖨️",
      "⌨️",
      "🖱️",
      "🖲️",
      "💾",
      "💿",
      "📀",
      "📷",
      "📸",
      "📹",
      "🎥",
      "📽️",
      "📺",
      "📻",
      "🎙️",
      "🎚️",
      "🎛️",
      "📡",
      "🔋",
      "🔌",
      // Lumiere
      "💡",
      "🔦",
      "🕯️",
      "🪔",
      // Bureau
      "📈",
      "📉",
      "📊",
      "📋",
      "📌",
      "📍",
      "📎",
      "🖇️",
      "📏",
      "📐",
      "✂️",
      "🗃️",
      "🗄️",
      "🗑️",
      // Ecriture
      "✏️",
      "✒️",
      "🖊️",
      "🖋️",
      "📝",
      "📓",
      "📒",
      "📔",
      // Livres & papier
      "📕",
      "📗",
      "📘",
      "📙",
      "📖",
      "📚",
      "📃",
      "📜",
      "📄",
      "📰",
      "🗞️",
      "📑",
      "🔖",
      "🏷️",
      // Courrier
      "✉️",
      "📧",
      "📨",
      "📩",
      "📤",
      "📥",
      "📦",
      "📫",
      "📬",
      "📭",
      "📮",
      // Argent
      "💳",
      "💰",
      "💵",
      "💶",
      "💷",
      "💴",
      "💲",
      "🧾",
      "💎",
      // Outils
      "🔒",
      "🔓",
      "🔑",
      "🗝️",
      "🔨",
      "🪓",
      "⛏️",
      "🔧",
      "🪛",
      "🔩",
      "⚙️",
      "🧲",
      "🪜",
      "🧰",
      "🪚",
      "🔗",
      "🧱",
      // Temps
      "⏰",
      "⏱️",
      "⏲️",
      "🕐",
      "🕑",
      "🕒",
      "🕓",
      "🕔",
      "🕕",
      "🕖",
      "🕗",
      "🕘",
      "🕙",
      "🕚",
      "🕛",
      // Calendrier
      "📅",
      "📆",
      "🗓️",
      // Maison
      "🛋️",
      "🪑",
      "🚪",
      "🪞",
      "🧹",
      "🧺",
      "🧼",
      "🪣",
      "🧽",
      // Autres
      "🎒",
      "👜",
      "👝",
      "🧳",
      "👑",
      "👒",
      "🎩",
      "🧢",
      "💍",
      "👓",
      "🕶️",
      "🥽",
      "🩹",
      "💊",
      "🩺",
      "🧬",
      "🔬",
      "🔭",
      "🧪",
      "🧫",
    ],
  },
  {
    name: "Symboles",
    icon: "❤️",
    emojis: [
      // Coeurs
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "❤️‍🔥",
      "❤️‍🩹",
      "💔",
      "❣️",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
      "💟",
      "♥️",
      // Geometrie & formes
      "🔴",
      "🟠",
      "🟡",
      "🟢",
      "🔵",
      "🟣",
      "⚫",
      "⚪",
      "🟤",
      "🔶",
      "🔷",
      "🔸",
      "🔹",
      "▪️",
      "▫️",
      "◼️",
      "◻️",
      "◾",
      "◽",
      "🔲",
      "🔳",
      "💠",
      // Validation
      "✔️",
      "☑️",
      "✅",
      "❌",
      "❎",
      "🚫",
      "⛔",
      // Fleches
      "➡️",
      "⬅️",
      "⬆️",
      "⬇️",
      "↗️",
      "↘️",
      "↙️",
      "↖️",
      "↕️",
      "↔️",
      "↩️",
      "↪️",
      "⤴️",
      "⤵️",
      "🔄",
      "🔃",
      "🔀",
      "🔁",
      "🔂",
      // Math
      "➕",
      "➖",
      "➗",
      "✖️",
      "♾️",
      "💲",
      // Info & ponctuation
      "❗",
      "❕",
      "❓",
      "❔",
      "‼️",
      "⁉️",
      "ℹ️",
      // Bulles
      "💬",
      "💭",
      "🗯️",
      "🗨️",
      // Effets
      "💤",
      "💢",
      "💣",
      "💥",
      "💦",
      "💨",
      "🕳️",
      "💫",
      "✨",
      "🌟",
      // Feu & elements
      "⚡",
      "🔥",
      "🌈",
      "☀️",
      // Signes
      "♻️",
      "⚜️",
      "🔱",
      "📛",
      "🔰",
      "⭕",
      "☢️",
      "☣️",
      "📵",
      "🚷",
      "🚯",
      "🚳",
      "🚱",
      "🔞",
      "📵",
      // Legal
      "©️",
      "®️",
      "™️",
      // Zodiaque
      "♈",
      "♉",
      "♊",
      "♋",
      "♌",
      "♍",
      "♎",
      "♏",
      "♐",
      "♑",
      "♒",
      "♓",
      "⛎",
      // Boutons
      "🔀",
      "🔁",
      "🔂",
      "▶️",
      "⏩",
      "⏭️",
      "⏯️",
      "◀️",
      "⏪",
      "⏮️",
      "🔼",
      "⏫",
      "🔽",
      "⏬",
      "⏸️",
      "⏹️",
      "⏺️",
      "⏏️",
      "🔅",
      "🔆",
      "📶",
      "🔈",
      "🔉",
      "🔊",
      "🔇",
      // Divers
      "🏧",
      "🚻",
      "🚹",
      "🚺",
      "♿",
      "🚼",
      "🛗",
      "⚠️",
      "🚨",
      "🔔",
      "🔕",
      "📣",
      "📢",
      "🔍",
      "🔎",
    ],
  },
  {
    name: "Drapeaux",
    icon: "🏳️",
    emojis: [
      "🏳️",
      "🏴",
      "🏁",
      "🚩",
      "🏳️‍🌈",
      "🏳️‍⚧️",
      "🏴‍☠️",
      "🇫🇷",
      "🇺🇸",
      "🇬🇧",
      "🇩🇪",
      "🇪🇸",
      "🇮🇹",
      "🇵🇹",
      "🇧🇪",
      "🇨🇭",
      "🇦🇹",
      "🇳🇱",
      "🇮🇪",
      "🇸🇪",
      "🇳🇴",
      "🇩🇰",
      "🇫🇮",
      "🇵🇱",
      "🇬🇷",
      "🇷🇴",
      "🇭🇺",
      "🇨🇦",
      "🇲🇽",
      "🇧🇷",
      "🇦🇷",
      "🇨🇴",
      "🇨🇱",
      "🇵🇪",
      "🇯🇵",
      "🇰🇷",
      "🇨🇳",
      "🇮🇳",
      "🇹🇭",
      "🇻🇳",
      "🇮🇩",
      "🇵🇭",
      "🇹🇷",
      "🇷🇺",
      "🇺🇦",
      "🇮🇱",
      "🇸🇦",
      "🇦🇪",
      "🇶🇦",
      "🇲🇦",
      "🇩🇿",
      "🇹🇳",
      "🇪🇬",
      "🇸🇳",
      "🇨🇮",
      "🇨🇲",
      "🇳🇬",
      "🇿🇦",
      "🇰🇪",
      "🇬🇭",
      "🇦🇺",
      "🇳🇿",
    ],
  },
];

interface EmojiPickerProps {
  onSelect: (emoji: string) => void;
  onClose: () => void;
}

export function EmojiPicker({ onSelect, onClose }: EmojiPickerProps) {
  const [activeCategory, setActiveCategory] = useState(0);
  const [search, setSearch] = useState("");

  const allEmojis = useMemo(
    () =>
      EMOJI_CATEGORIES.flatMap((c) =>
        c.emojis.map((e) => ({ emoji: e, category: c.name })),
      ),
    [],
  );

  // Index inverse pour la recherche : emoji -> mots-cles
  const emojiToKeywords = useMemo(() => {
    const map = new Map<string, string[]>();
    for (const [keyword, emojis] of Object.entries(EMOJI_NAMES)) {
      for (const emoji of emojis) {
        const existing = map.get(emoji) || [];
        existing.push(keyword);
        map.set(emoji, existing);
      }
    }
    return map;
  }, []);

  const filtered = useMemo(() => {
    if (!search.trim()) {
      return EMOJI_CATEGORIES[activeCategory].emojis.map((e) => ({
        emoji: e,
        category: "",
      }));
    }

    const query = search.toLowerCase().trim();
    const seen = new Set<string>();
    const results: { emoji: string; category: string }[] = [];

    for (const item of allEmojis) {
      if (seen.has(item.emoji)) continue;

      // Cherche dans le nom de catégorie
      const matchCategory = item.category.toLowerCase().includes(query);

      // Cherche dans les mots-cles
      const keywords = emojiToKeywords.get(item.emoji) || [];
      const matchKeyword = keywords.some((kw) => kw.includes(query));

      // Cherche dans l'emoji lui-meme
      const matchEmoji = item.emoji.includes(search);

      if (matchCategory || matchKeyword || matchEmoji) {
        seen.add(item.emoji);
        results.push(item);
      }
    }

    return results;
  }, [search, activeCategory, allEmojis, emojiToKeywords]);

  return (
    <>
      <div className="fixed inset-0 z-10" onClick={onClose} />
      <div
        className="absolute bottom-full right-0 mb-2 bg-surface border border-border rounded-xl shadow-lg w-80 overflow-hidden z-20"
        data-emoji-picker
      >
        {/* Search */}
        <div className="px-3 pt-3 pb-2">
          <div className="relative">
            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
            <input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Rechercher un emoji..."
              className="w-full h-8 rounded-lg border border-transparent bg-muted/50 pl-8 pr-3 text-xs text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:border-primary/40 focus:ring-1 focus:ring-primary/20 transition-all"
              autoFocus
            />
          </div>
        </div>

        {/* Category tabs */}
        {!search && (
          <div className="flex px-2 gap-0.5 overflow-x-auto scrollbar-hide">
            {EMOJI_CATEGORIES.map((cat, i) => (
              <button
                key={cat.name}
                onClick={() => setActiveCategory(i)}
                className={`shrink-0 w-8 h-8 flex items-center justify-center rounded-lg text-sm transition-colors ${
                  activeCategory === i ? "bg-primary/10" : "hover:bg-muted"
                }`}
                title={cat.name}
              >
                {cat.icon}
              </button>
            ))}
          </div>
        )}

        {/* Category label */}
        {!search && (
          <div className="px-3 pt-2 pb-1">
            <span className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider">
              {EMOJI_CATEGORIES[activeCategory].name}
            </span>
          </div>
        )}

        {/* Emojis grid */}
        <div className="px-2 pb-2 grid grid-cols-8 gap-0.5 max-h-72 overflow-y-auto">
          {filtered.map((item, i) => (
            <button
              key={`${item.emoji}-${i}`}
              onClick={() => {
                onSelect(item.emoji);
                onClose();
              }}
              className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-muted transition-colors text-lg"
            >
              {item.emoji}
            </button>
          ))}
          {filtered.length === 0 && (
            <p className="col-span-8 text-center text-xs text-muted-foreground py-4">
              Aucun emoji trouve
            </p>
          )}
        </div>
      </div>
    </>
  );
}
